### ISSUE TITLE
Alternative license?

### ISSUE THREAD

**Issue by pombredanne** [inveniosoftware/intbitset#36]
Hi I was wondering if you would consider an alternative license (like the LGPL or else) to make it easier to integrate this library ... as a library in a larger Apache-licensed project (scancode-toolkit).
Thank you for you kind consideration!

**Comment by jirikuncar** [comment]
cc @tiborsimko @kaplun

**Comment by kaplun** [comment]
I personally don't have a strong opinion on the subject. The original license was the Invenio one from which the library stemmed off.

I guess we could switch to more liberal licenses such as the Revised BSD License used by Beard. 

@tiborsimko ?

**Comment by lnielsen** [comment]
CERN rules apply since intbitset is copyright by CERN. Rules however allow for using LGPLv3 for special cases such as libraries so I think it should be possible to change to LGPLv3. See https://cds.cern.ch/record/1482206/files/OSL-2012-01-Open%20Source%20Licences%20at%20CERN-Short%20version.pdf

**Comment by pombredanne** [comment]
Thank you for the quick response. LGPL would be awesome for a library.

**Comment by kaplun** [comment]
Just for my education, to simply have `intbitset` as a dependency for your project, would indeed be a source of license conflict?

**Comment by pombredanne** [comment]
@kaplun For GPL my understanding is yes when used as a library. And this is why the LGPL and GPL with linking exceptions were created in the first place as far as I know.

**Comment by pombredanne** [comment]
BTW FWIW, you also release other CERN-copyrighted software under a BSD license https://github.com/inveniosoftware/dojson/blob/master/LICENSE

**Comment by lnielsen** [comment]
@pombredanne Yes, there's a possibility for exceptions when GPL or LGPL would hinder uptake of a  library - we've primarily used BSD for e.g. Flask extensions.

**Comment by tiborsimko** [comment]
The LGPL seems reasonable for `intbitset`.  Ideally, we should contact all authors in order to approve/disapprove such a licence change, as we did in the past (see e.g. https://github.com/inveniosoftware/flask-registry/pull/29). I'll start the movement below. Fortunately we are not that many people :smile:  CC @Osso @jirikuncar @lnielsen @crepererum @kaplun @NikolaYolov @tiborsimko

**Comment by tiborsimko** [comment]
Tibor Simko (@tiborsimko) agrees with the license change to LGPL.

**Comment by jirikuncar** [comment]
Jiri Kuncar (@jirikuncar) agrees with the license change to the GNU LGPL.

**Comment by crepererum** [comment]
Can we set a target version (i.e. GNU LGPL v2, v2.1 or v3) please? This would avoid confusions and legal problems afterwards.

**Comment by NikolaYolov** [comment]
Nikola Yolov (@NikolaYolov) <https://github.com/NikolaYolov> agrees with 
the license change to the GNU LGPL.
(He also misses CERN and says hi to everyone.)

**Comment by tiborsimko** [comment]
> Can we set a target version (i.e. GNU LGPL v2, v2.1 or v3) please? This would avoid confusions and legal problems afterwards.

I'd say the latest one, LGPLv3, unless there are objections?

> He also misses CERN and says hi to everyone.

Hi! :smile:

**Comment by crepererum** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I (Marco Neumann, @crepererum) agree with the license change of
`inveniosoftware/intbitset` from GPLv2 to LGPLv3.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJXC9QxAAoJEJGh8JABaxzCaI0QAMbXgz2+NqTMmZdE2K1BclhT
8n4Y0/Yp4UPREWJPIfjuilNE0TRrVudVckfitwnlhhizU/GdVCB3NeYgF9XOBIsb
Tu2vy8yPRAjEkMaDwf8Y5Xz1OlBcrdbeERpXuAT8yy7zyKnhZbFzCaNzIBQiQGT1
SCXqybJwJ/nhfJoQ7xr1cj56j5wwpU0aaViyq1dvxdBtZB3ImcaSvEf4wSE0ZN52
p66BboP+YRpTIfSuqXVpL+oNgfcHyFexNzcY2LKoEMzNLWwuQkynfjjqE6yzubJv
DyMtTA3YxYDL4p+I4y+PQVfqrLkTRA7tUTAlb0DU+wz7QDgVc8XC1ljGu68AHSzh
y/NeM2K+RsDGM7SUFsL3nT30GUW6OKq7D3U37toNw8zFzjFDx57eaCjQZN9533iv
d8m1isejdmU4kEjjnr8MOfp4NbnMS/KykkroP37PnslSEF9twtBWlHnmBLzmByJN
IGTmdUEC4xAep5nZrHIFtwgBVefKD5xbWhtiuzS5vMKFJL/CdjYEDdfaIg+v9H5d
IvBtC3eR+4vYhMhu8Bb5BD3bY8dwkJdkj4zwIYyOFmZRHnpSHsRVCGxDqs+PI/R9
fXPMHEPaR+VwroiLy92Hz20zy91TLZddE5axic3Q7MtjiHMZ0nA/s9huyZCIRxK8
Rq+nKwNxLDwOlax2W7DT
=wEJK
-----END PGP SIGNATURE-----
```

**Comment by kaplun** [comment]
Samuele (@samuelekaplun) agrees with the license change to the GNU LGPL.

P.s. how would you do realistically if we were to change the license of a module with much larger number of contributors? I guess we need to better elect some maintainers...

**Comment by tiborsimko** [comment]
@kaplun I don't think it's possible to change licence without explicit agreement of all the contributors... which is why it's important to get the licence choice right from the get go, ideally.

P.S. BTW see FSF's advice on [why you shouldn't use the Lesser GPL for your next library](https://www.gnu.org/licenses/why-not-lgpl.html)...

**Comment by lnielsen** [comment]
Lars Holm Nielsen (@lnielsen) agrees with the license change to the GNU LGPLv3.

However, why do contributors need to agree to the license change? There's two classes:

- Employees of CERN (at the time of contributing): Everything they produce of code is IP of CERN.
- External contributors: Are asked to agree to the license and that CERN is the copyright holder. 

I.e. CERN has the full copyright and can do what they want with it or I am missing something?

**Comment by tiborsimko** [comment]
Yes, the copyright is CERN, and there is no doubt about it.  However, regarding the licence, there is a choice, unlike for copyright. So it's good manners to get an agreement of all contributors in case of a licence change, simply because that's not the original licence under which people were willingly contributing code, and they may have some reasonable objections regarding the suggested new licence. 

(Even though in practice, it seems highly improbable that people would e.g. refuse CERN internship because of concerns of having to work within LGPL rather than GPL...)

**Comment by pombredanne** [comment]
@tiborsimko wrote:
> (Even though in practice, it seems highly improbable that people would e.g. refuse CERN internship because of concerns of having to work within LGPL rather than GPL...)

Actually I have heard from someone and therefore know for a fact that two person did such thing in the past: but they were immediately annihilated in a particle accelerator.

**Comment by crepererum** [comment]
I agree with the opinion of @lnielsen. During the time I've worked on `intbitset`, I was employed by CERN and therefor they are allowed to do whatever the want with the code (as long as it doesn't affect me as a person or my personal work, e.g. by making people responsible for the code afterwards, which isn't the case here). A problem that might appear (not for me but for others): sometimes you may have contributions that where handed in after a certain contract ended and therefore that contribution is not a CERN IP. That's a general "problem" of Open Source projects without dedicated internal and external repos.

The discussion we have here is basically the reason why most projects out there let external contributors sign a CLA. I kinda remember that we had the discussion about a general Invenio CLA before, but didn't came to a conclusion because a) there needs to be a check by some lawyers and b) most contributors are working for CERN or Tind anyway.

Even I'm not part of the team anymore but I would suggest the following scheme: let everyone sign a CLA, including your employers. That also "defuses" the "end of contract" edge case described above.

On the other hand: it is really polite to ask for the license change and I'm very happy being asked. :+1:

**Comment by Osso** [comment]
Sure I am fine with whatever license you can come up with. (I'm quite fond of the MIT license myself)

**Comment by kaplun** [comment]
@tiborsimko I think everybody agreed on the change of license.

**Comment by pombredanne** [comment]
:+1: Thank you to everyone for this effort. Mucho appreciated.

**Comment by tiborsimko** [comment]
@pombredanne This week is kind of crazy, but hopefully we'll get to releasing the license changed version next week.

**Comment by pombredanne** [comment]
@tiborsimko no rush :)

**Comment by pombredanne** [comment]
@kaplun @tiborsimko and team: Thank you very much!
